### PR TITLE
Support for thoth unresolved-package-handler

### PR DESCRIPTION
**Pull request by harshad16**
Support for thoth unresolved-package-handler
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Review by pacospace — APPROVED** [review]

**Comment by pacospace** [comment]
recheck

**Comment by pacospace** [comment]
recheck

**Comment by harshad16** [comment]
recheck

**Review by goern — APPROVED** [review]

**Comment by goern** [comment]
recheck

**Comment by pacospace** [comment]
recheck

**Comment by harshad16** [comment]
Merging it, will look into the issue personally.

**Pull request merged**
