### PR TITLE
Added jupyter-notebook.yaml

### PR DESCRIPTION
**Pull request by ace2107**
Added in zuul jupyter-notebook.yaml

### CODE REVIEW

**Comment by goern** [comment]
@ace2107 ping

**Comment by ace2107** [comment]
I am unable to see what is failing . Not sure what is wrong

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Comment by ghost** [comment]
Build succeeded.

- [config-check ](https://zuul.thoth-station.ninja/logs/4/4/94b6e57d28885861f3062430910c91e7dcfd9383/check/config-check/1b6f4ef/) : SUCCESS in 5m 19s

**Pull request closed without merging**
